### ISSUE TITLE
log retrieval command

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon-ssh-portal#149]
It could be handy to be able to retrieve logs for a service/container using SSH.

I would envision this as something like the following maybe, and it just dumps the current logs of that pod/container. This would help in cases where operators of Lagoon may not have logging installed, but still want developers to be able to view container logs some how.

```
$ ssh project-environment@ssh.host service=nginx container=nginx logs=true
Setting up Healthz routing
Healthz routing - using PHP
10.42.4.0 - - [08/Dec/2022:07:32:06 +0000] "GET /........
```

**Comment by tobybellwood** [comment]
yeah, now we have ssh-portal using NATS, real-time streaming of logs is far more achievable. This makes sense to explore.

**Comment by shreddedbacon** [comment]
Dump and stream as separate options perhaps.

Being able to dump to a file and share easily, or streaming to try and capture an event in real-time.

Dump would be far easier to implement initially, streaming later.

**Comment by smlx** [comment]
This is a neat idea! And probably not too hard to implement.

My question would be: does it need to be a separate permission to exec? Or would you be happy to have "can exec" == "can stream logs". We probably need to document this in the RBAC matrix.

**Comment by shreddedbacon** [comment]
> My question would be: does it need to be a separate permission to exec? Or would you be happy to have "can exec" == "can stream logs". We probably need to document this in the RBAC matrix.

I think if you can exec, you can get logs. I don't see a reason to have a separate permission scope for it? But happy to be convinced otherwise if there is a compelling reason?

**Comment by shreddedbacon** [comment]
Have you got a working-ish version of this we can look at?
